# Generated by Django 3.0.6 on 2020-06-05 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchaser', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Not required. +1 before phone number', max_length=128, region=None)),
                ('address', models.CharField(blank=True, help_text='Not required until appointment is confirmed', max_length=50)),
                ('cubic_yards', models.PositiveIntegerField(help_text='$25-35/cu. yard')),
                ('weeding', models.BooleanField(help_text='$5/cu. yard')),
                ('edging', models.BooleanField(help_text='$0.60/foot')),
                ('delivery', models.CharField(choices=[('P', 'I will set up the mulch delivery'), ('M', 'I would like MulchMen to set up the mulch delivery')], default='P', max_length=1)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Scheduled'), ('C', 'Completed')], default='P', max_length=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sumbitted_at', models.DateTimeField(auto_now_add=True)),
                ('hear_about_us', models.CharField(help_text='Facebook, reference, etc', max_length=100)),
                ('additional_comments', models.CharField(blank=True, help_text='Type of mulch, delivery instructions, quantity of mulch confusion, speical requests, etc', max_length=2000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
