# Generated by Django 3.0.6 on 2020-06-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='key',
            field=models.CharField(default='20', max_length=50),
        ),
    ]
