# Generated by Django 3.0.6 on 2020-06-08 18:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20200608_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Not required', max_length=128, region='US'),
        ),
    ]
