# Generated by Django 3.0.6 on 2020-06-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20200608_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bed_cleaning',
            field=models.BooleanField(default=False, help_text='$5/cu. yard'),
        ),
    ]
